import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import vitest from "ultracite/oxlint/vitest";

export default defineConfig({
  extends: [core, react, vitest],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Nested pnpm workspace for the Blume site — own lockfile and deps
    // (blume isn't installed at the root, so type-aware lint can't
    // resolve its imports here).
    "docs/**",
    // Generated by `shadcn add` — maintained upstream, not hand-edited.
    "src/components/**",
    "src/hooks/**",
    "src/lib/**",
  ],
  jsPlugins: [{ name: "complexity", specifier: "oxlint-plugin-complexity" }],
  options: { typeAware: true, typeCheck: true },
  overrides: [
    {
      files: [
        "**/*.{test,spec,test-d,spec-d}.{ts,tsx,js,jsx}",
        "**/__tests__/**/*.{ts,tsx,js,jsx}",
      ],
      rules: {
        // describe/it nesting dominates the metric, not actual logic.
        "complexity/complexity": "off",
      },
    },
  ],
  rules: {
    // eslint/complexity only covers cyclomatic; the plugin checks both
    // cyclomatic and cognitive complexity in a single pass.
    complexity: "off",
    "complexity/complexity": ["warn", { cognitive: 15, cyclomatic: 20 }],
  },
});
