import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";
import react from "ultracite/oxlint/react";
import vitest from "ultracite/oxlint/vitest";

export default defineConfig({
  extends: [core, react, vitest],
  ignorePatterns: [
    ...(core.ignorePatterns ?? []),
    // Generated by `shadcn add` — maintained upstream, not hand-edited.
    "src/components/**",
    "src/hooks/**",
    "src/lib/**",
  ],
  options: { typeAware: true, typeCheck: true },
});
