// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Kbd, KbdGroup } from "../components/wireframe/ui/kbd.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeKbd = /* @__PURE__ */ wrapWireframe("Kbd", Kbd, "kbd");
export const WireframeKbdGroup = /* @__PURE__ */ wrapWireframe(
  "KbdGroup",
  KbdGroup,
  "kbd"
);
