// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardAction,
  CardDescription,
  CardContent,
} from "../components/wireframe/ui/card.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeCard = /* @__PURE__ */ wrapWireframe(
  "Card",
  Card,
  "card"
);
export const WireframeCardHeader = /* @__PURE__ */ wrapWireframe(
  "CardHeader",
  CardHeader,
  "card"
);
export const WireframeCardFooter = /* @__PURE__ */ wrapWireframe(
  "CardFooter",
  CardFooter,
  "card"
);
export const WireframeCardTitle = /* @__PURE__ */ wrapWireframe(
  "CardTitle",
  CardTitle,
  "card"
);
export const WireframeCardAction = /* @__PURE__ */ wrapWireframe(
  "CardAction",
  CardAction,
  "card"
);
export const WireframeCardDescription = /* @__PURE__ */ wrapWireframe(
  "CardDescription",
  CardDescription,
  "card"
);
export const WireframeCardContent = /* @__PURE__ */ wrapWireframe(
  "CardContent",
  CardContent,
  "card"
);
