// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Stack } from "../components/wireframe/ui/stack.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeStack = /* @__PURE__ */ wrapWireframe(
  "Stack",
  Stack,
  "stack"
);
