// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Badge, BadgeWireframe } from "../components/wireframe/ui/badge.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeBadge = /* @__PURE__ */ wrapWireframe(
  "Badge",
  Badge,
  "badge"
);
export const WireframeBadgeWireframe = /* @__PURE__ */ wrapWireframe(
  "BadgeWireframe",
  BadgeWireframe,
  "badge"
);
