// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Checkbox } from "../components/wireframe/ui/checkbox.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeCheckbox = /* @__PURE__ */ wrapWireframe(
  "Checkbox",
  Checkbox,
  "checkbox"
);
