// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Toaster,
  SonnerWireframeExample,
} from "../components/wireframe/ui/sonner.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeToaster = /* @__PURE__ */ wrapWireframe(
  "Toaster",
  Toaster,
  "sonner"
);
export const WireframeSonnerWireframeExample = /* @__PURE__ */ wrapWireframe(
  "SonnerWireframeExample",
  SonnerWireframeExample,
  "sonner"
);
