// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { ListGroup } from "../components/wireframe/ui/list-group.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeListGroup = /* @__PURE__ */ wrapWireframe(
  "ListGroup",
  ListGroup,
  "list-group"
);
export const WireframeList = WireframeListGroup;
