// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
  DrawerWireframeExample,
} from "../components/wireframe/ui/drawer.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeDrawer = /* @__PURE__ */ wrapWireframe(
  "Drawer",
  Drawer,
  "drawer"
);
export const WireframeDrawerPortal = /* @__PURE__ */ wrapWireframe(
  "DrawerPortal",
  DrawerPortal,
  "drawer"
);
export const WireframeDrawerOverlay = /* @__PURE__ */ wrapWireframe(
  "DrawerOverlay",
  DrawerOverlay,
  "drawer"
);
export const WireframeDrawerTrigger = /* @__PURE__ */ wrapWireframe(
  "DrawerTrigger",
  DrawerTrigger,
  "drawer"
);
export const WireframeDrawerClose = /* @__PURE__ */ wrapWireframe(
  "DrawerClose",
  DrawerClose,
  "drawer"
);
export const WireframeDrawerContent = /* @__PURE__ */ wrapWireframe(
  "DrawerContent",
  DrawerContent,
  "drawer"
);
export const WireframeDrawerHeader = /* @__PURE__ */ wrapWireframe(
  "DrawerHeader",
  DrawerHeader,
  "drawer"
);
export const WireframeDrawerFooter = /* @__PURE__ */ wrapWireframe(
  "DrawerFooter",
  DrawerFooter,
  "drawer"
);
export const WireframeDrawerTitle = /* @__PURE__ */ wrapWireframe(
  "DrawerTitle",
  DrawerTitle,
  "drawer"
);
export const WireframeDrawerDescription = /* @__PURE__ */ wrapWireframe(
  "DrawerDescription",
  DrawerDescription,
  "drawer"
);
export const WireframeDrawerWireframeExample = /* @__PURE__ */ wrapWireframe(
  "DrawerWireframeExample",
  DrawerWireframeExample,
  "drawer"
);
