// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupText,
  InputGroupInput,
  InputGroupTextarea,
} from "../components/wireframe/ui/input-group.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeInputGroup = /* @__PURE__ */ wrapWireframe(
  "InputGroup",
  InputGroup,
  "input-group"
);
export const WireframeInputGroupAddon = /* @__PURE__ */ wrapWireframe(
  "InputGroupAddon",
  InputGroupAddon,
  "input-group"
);
export const WireframeInputGroupButton = /* @__PURE__ */ wrapWireframe(
  "InputGroupButton",
  InputGroupButton,
  "input-group"
);
export const WireframeInputGroupText = /* @__PURE__ */ wrapWireframe(
  "InputGroupText",
  InputGroupText,
  "input-group"
);
export const WireframeInputGroupInput = /* @__PURE__ */ wrapWireframe(
  "InputGroupInput",
  InputGroupInput,
  "input-group"
);
export const WireframeInputGroupTextarea = /* @__PURE__ */ wrapWireframe(
  "InputGroupTextarea",
  InputGroupTextarea,
  "input-group"
);
