// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Label } from "../components/wireframe/ui/label.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeLabel = /* @__PURE__ */ wrapWireframe(
  "Label",
  Label,
  "label"
);
