// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Media } from "../components/wireframe/ui/media.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeMedia = /* @__PURE__ */ wrapWireframe(
  "Media",
  Media,
  "media"
);
