// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
  ChartStyle,
  ChartWireframe,
} from "../components/wireframe/ui/chart.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeChartContainer = /* @__PURE__ */ wrapWireframe(
  "ChartContainer",
  ChartContainer,
  "chart"
);
export const WireframeChartTooltip = /* @__PURE__ */ wrapWireframe(
  "ChartTooltip",
  ChartTooltip,
  "chart"
);
export const WireframeChartTooltipContent = /* @__PURE__ */ wrapWireframe(
  "ChartTooltipContent",
  ChartTooltipContent,
  "chart"
);
export const WireframeChartLegend = /* @__PURE__ */ wrapWireframe(
  "ChartLegend",
  ChartLegend,
  "chart"
);
export const WireframeChartLegendContent = /* @__PURE__ */ wrapWireframe(
  "ChartLegendContent",
  ChartLegendContent,
  "chart"
);
export const WireframeChartStyle = /* @__PURE__ */ wrapWireframe(
  "ChartStyle",
  ChartStyle,
  "chart"
);
export const WireframeChartWireframe = /* @__PURE__ */ wrapWireframe(
  "ChartWireframe",
  ChartWireframe,
  "chart"
);
export const WireframeChart = WireframeChartWireframe;
