// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { HeroSection } from "../components/wireframe/blocks/hero-section.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeHeroSection = /* @__PURE__ */ wrapWireframe(
  "HeroSection",
  HeroSection,
  "hero-section",
  true
);
