// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarGroup,
  SidebarGroupAction,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarHeader,
  SidebarInput,
  SidebarInset,
  SidebarMenu,
  SidebarMenuAction,
  SidebarMenuBadge,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarMenuSkeleton,
  SidebarMenuSub,
  SidebarMenuSubButton,
  SidebarMenuSubItem,
  SidebarProvider,
  SidebarRail,
  SidebarSeparator,
  SidebarTrigger,
  SidebarGroupLabelWireframe,
  SidebarMenuButtonWireframe,
} from "../components/wireframe/ui/sidebar.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSidebar = /* @__PURE__ */ wrapWireframe(
  "Sidebar",
  Sidebar,
  "sidebar"
);
export const WireframeSidebarContent = /* @__PURE__ */ wrapWireframe(
  "SidebarContent",
  SidebarContent,
  "sidebar"
);
export const WireframeSidebarFooter = /* @__PURE__ */ wrapWireframe(
  "SidebarFooter",
  SidebarFooter,
  "sidebar"
);
export const WireframeSidebarGroup = /* @__PURE__ */ wrapWireframe(
  "SidebarGroup",
  SidebarGroup,
  "sidebar"
);
export const WireframeSidebarGroupAction = /* @__PURE__ */ wrapWireframe(
  "SidebarGroupAction",
  SidebarGroupAction,
  "sidebar"
);
export const WireframeSidebarGroupContent = /* @__PURE__ */ wrapWireframe(
  "SidebarGroupContent",
  SidebarGroupContent,
  "sidebar"
);
export const WireframeSidebarGroupLabel = /* @__PURE__ */ wrapWireframe(
  "SidebarGroupLabel",
  SidebarGroupLabel,
  "sidebar"
);
export const WireframeSidebarHeader = /* @__PURE__ */ wrapWireframe(
  "SidebarHeader",
  SidebarHeader,
  "sidebar"
);
export const WireframeSidebarInput = /* @__PURE__ */ wrapWireframe(
  "SidebarInput",
  SidebarInput,
  "sidebar"
);
export const WireframeSidebarInset = /* @__PURE__ */ wrapWireframe(
  "SidebarInset",
  SidebarInset,
  "sidebar"
);
export const WireframeSidebarMenu = /* @__PURE__ */ wrapWireframe(
  "SidebarMenu",
  SidebarMenu,
  "sidebar"
);
export const WireframeSidebarMenuAction = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuAction",
  SidebarMenuAction,
  "sidebar"
);
export const WireframeSidebarMenuBadge = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuBadge",
  SidebarMenuBadge,
  "sidebar"
);
export const WireframeSidebarMenuButton = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuButton",
  SidebarMenuButton,
  "sidebar"
);
export const WireframeSidebarMenuItem = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuItem",
  SidebarMenuItem,
  "sidebar"
);
export const WireframeSidebarMenuSkeleton = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuSkeleton",
  SidebarMenuSkeleton,
  "sidebar"
);
export const WireframeSidebarMenuSub = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuSub",
  SidebarMenuSub,
  "sidebar"
);
export const WireframeSidebarMenuSubButton = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuSubButton",
  SidebarMenuSubButton,
  "sidebar"
);
export const WireframeSidebarMenuSubItem = /* @__PURE__ */ wrapWireframe(
  "SidebarMenuSubItem",
  SidebarMenuSubItem,
  "sidebar"
);
export const WireframeSidebarProvider = /* @__PURE__ */ wrapWireframe(
  "SidebarProvider",
  SidebarProvider,
  "sidebar"
);
export const WireframeSidebarRail = /* @__PURE__ */ wrapWireframe(
  "SidebarRail",
  SidebarRail,
  "sidebar"
);
export const WireframeSidebarSeparator = /* @__PURE__ */ wrapWireframe(
  "SidebarSeparator",
  SidebarSeparator,
  "sidebar"
);
export const WireframeSidebarTrigger = /* @__PURE__ */ wrapWireframe(
  "SidebarTrigger",
  SidebarTrigger,
  "sidebar"
);
export const WireframeSidebarGroupLabelWireframe =
  /* @__PURE__ */ wrapWireframe(
    "SidebarGroupLabelWireframe",
    SidebarGroupLabelWireframe,
    "sidebar"
  );
export const WireframeSidebarMenuButtonWireframe =
  /* @__PURE__ */ wrapWireframe(
    "SidebarMenuButtonWireframe",
    SidebarMenuButtonWireframe,
    "sidebar"
  );
