// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Table,
  TableHeader,
  TableBody,
  TableFooter,
  TableHead,
  TableRow,
  TableCell,
  TableCaption,
  TableCellWireframe,
  TableHeadWireframe,
} from "../components/wireframe/ui/table.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeTable = /* @__PURE__ */ wrapWireframe(
  "Table",
  Table,
  "table"
);
export const WireframeTableHeader = /* @__PURE__ */ wrapWireframe(
  "TableHeader",
  TableHeader,
  "table"
);
export const WireframeTableBody = /* @__PURE__ */ wrapWireframe(
  "TableBody",
  TableBody,
  "table"
);
export const WireframeTableFooter = /* @__PURE__ */ wrapWireframe(
  "TableFooter",
  TableFooter,
  "table"
);
export const WireframeTableHead = /* @__PURE__ */ wrapWireframe(
  "TableHead",
  TableHead,
  "table"
);
export const WireframeTableRow = /* @__PURE__ */ wrapWireframe(
  "TableRow",
  TableRow,
  "table"
);
export const WireframeTableCell = /* @__PURE__ */ wrapWireframe(
  "TableCell",
  TableCell,
  "table"
);
export const WireframeTableCaption = /* @__PURE__ */ wrapWireframe(
  "TableCaption",
  TableCaption,
  "table"
);
export const WireframeTableCellWireframe = /* @__PURE__ */ wrapWireframe(
  "TableCellWireframe",
  TableCellWireframe,
  "table"
);
export const WireframeTableHeadWireframe = /* @__PURE__ */ wrapWireframe(
  "TableHeadWireframe",
  TableHeadWireframe,
  "table"
);
