// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Button } from "../components/wireframe/ui/button.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeButton = /* @__PURE__ */ wrapWireframe(
  "Button",
  Button,
  "button"
);
