// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Pagination,
  PaginationContent,
  PaginationLink,
  PaginationItem,
  PaginationPrevious,
  PaginationNext,
  PaginationEllipsis,
} from "../components/wireframe/ui/pagination.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframePagination = /* @__PURE__ */ wrapWireframe(
  "Pagination",
  Pagination,
  "pagination"
);
export const WireframePaginationContent = /* @__PURE__ */ wrapWireframe(
  "PaginationContent",
  PaginationContent,
  "pagination"
);
export const WireframePaginationLink = /* @__PURE__ */ wrapWireframe(
  "PaginationLink",
  PaginationLink,
  "pagination"
);
export const WireframePaginationItem = /* @__PURE__ */ wrapWireframe(
  "PaginationItem",
  PaginationItem,
  "pagination"
);
export const WireframePaginationPrevious = /* @__PURE__ */ wrapWireframe(
  "PaginationPrevious",
  PaginationPrevious,
  "pagination"
);
export const WireframePaginationNext = /* @__PURE__ */ wrapWireframe(
  "PaginationNext",
  PaginationNext,
  "pagination"
);
export const WireframePaginationEllipsis = /* @__PURE__ */ wrapWireframe(
  "PaginationEllipsis",
  PaginationEllipsis,
  "pagination"
);
