// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPortal,
  DialogTitle,
  DialogTrigger,
  DialogWireframeExample,
} from "../components/wireframe/ui/dialog.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeDialog = /* @__PURE__ */ wrapWireframe(
  "Dialog",
  Dialog,
  "dialog"
);
export const WireframeDialogClose = /* @__PURE__ */ wrapWireframe(
  "DialogClose",
  DialogClose,
  "dialog"
);
export const WireframeDialogContent = /* @__PURE__ */ wrapWireframe(
  "DialogContent",
  DialogContent,
  "dialog"
);
export const WireframeDialogDescription = /* @__PURE__ */ wrapWireframe(
  "DialogDescription",
  DialogDescription,
  "dialog"
);
export const WireframeDialogFooter = /* @__PURE__ */ wrapWireframe(
  "DialogFooter",
  DialogFooter,
  "dialog"
);
export const WireframeDialogHeader = /* @__PURE__ */ wrapWireframe(
  "DialogHeader",
  DialogHeader,
  "dialog"
);
export const WireframeDialogOverlay = /* @__PURE__ */ wrapWireframe(
  "DialogOverlay",
  DialogOverlay,
  "dialog"
);
export const WireframeDialogPortal = /* @__PURE__ */ wrapWireframe(
  "DialogPortal",
  DialogPortal,
  "dialog"
);
export const WireframeDialogTitle = /* @__PURE__ */ wrapWireframe(
  "DialogTitle",
  DialogTitle,
  "dialog"
);
export const WireframeDialogTrigger = /* @__PURE__ */ wrapWireframe(
  "DialogTrigger",
  DialogTrigger,
  "dialog"
);
export const WireframeDialogWireframeExample = /* @__PURE__ */ wrapWireframe(
  "DialogWireframeExample",
  DialogWireframeExample,
  "dialog"
);
