// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "../components/wireframe/ui/accordion.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeAccordion = /* @__PURE__ */ wrapWireframe(
  "Accordion",
  Accordion,
  "accordion"
);
export const WireframeAccordionItem = /* @__PURE__ */ wrapWireframe(
  "AccordionItem",
  AccordionItem,
  "accordion"
);
export const WireframeAccordionTrigger = /* @__PURE__ */ wrapWireframe(
  "AccordionTrigger",
  AccordionTrigger,
  "accordion"
);
export const WireframeAccordionContent = /* @__PURE__ */ wrapWireframe(
  "AccordionContent",
  AccordionContent,
  "accordion"
);
