// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Toggle } from "../components/wireframe/ui/toggle.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeToggle = /* @__PURE__ */ wrapWireframe(
  "Toggle",
  Toggle,
  "toggle"
);
