// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Heading } from "../components/wireframe/ui/heading.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeHeading = /* @__PURE__ */ wrapWireframe(
  "Heading",
  Heading,
  "heading"
);
