// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { LoginForm } from "../components/wireframe/blocks/login-form.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeLoginForm = /* @__PURE__ */ wrapWireframe(
  "LoginForm",
  LoginForm,
  "login-form",
  true
);
