// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Separator } from "../components/wireframe/ui/separator.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSeparator = /* @__PURE__ */ wrapWireframe(
  "Separator",
  Separator,
  "separator"
);
