// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
} from "../components/wireframe/ui/tabs.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeTabs = /* @__PURE__ */ wrapWireframe(
  "Tabs",
  Tabs,
  "tabs"
);
export const WireframeTabsList = /* @__PURE__ */ wrapWireframe(
  "TabsList",
  TabsList,
  "tabs"
);
export const WireframeTabsTrigger = /* @__PURE__ */ wrapWireframe(
  "TabsTrigger",
  TabsTrigger,
  "tabs"
);
export const WireframeTabsContent = /* @__PURE__ */ wrapWireframe(
  "TabsContent",
  TabsContent,
  "tabs"
);
