// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Paragraph } from "../components/wireframe/ui/paragraph.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeParagraph = /* @__PURE__ */ wrapWireframe(
  "Paragraph",
  Paragraph,
  "paragraph"
);
