// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
  BreadcrumbEllipsis,
} from "../components/wireframe/ui/breadcrumb.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeBreadcrumb = /* @__PURE__ */ wrapWireframe(
  "Breadcrumb",
  Breadcrumb,
  "breadcrumb"
);
export const WireframeBreadcrumbList = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbList",
  BreadcrumbList,
  "breadcrumb"
);
export const WireframeBreadcrumbItem = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbItem",
  BreadcrumbItem,
  "breadcrumb"
);
export const WireframeBreadcrumbLink = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbLink",
  BreadcrumbLink,
  "breadcrumb"
);
export const WireframeBreadcrumbPage = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbPage",
  BreadcrumbPage,
  "breadcrumb"
);
export const WireframeBreadcrumbSeparator = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbSeparator",
  BreadcrumbSeparator,
  "breadcrumb"
);
export const WireframeBreadcrumbEllipsis = /* @__PURE__ */ wrapWireframe(
  "BreadcrumbEllipsis",
  BreadcrumbEllipsis,
  "breadcrumb"
);
