// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Pricing } from "../components/wireframe/blocks/pricing.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframePricing = /* @__PURE__ */ wrapWireframe(
  "Pricing",
  Pricing,
  "pricing",
  true
);
