// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Input } from "../components/wireframe/ui/input.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeInput = /* @__PURE__ */ wrapWireframe(
  "Input",
  Input,
  "input"
);
