// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { ProductGrid } from "../components/wireframe/blocks/product-grid.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeProductGrid = /* @__PURE__ */ wrapWireframe(
  "ProductGrid",
  ProductGrid,
  "product-grid",
  true
);
