// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Dashboard } from "../components/wireframe/blocks/dashboard.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeDashboard = /* @__PURE__ */ wrapWireframe(
  "Dashboard",
  Dashboard,
  "dashboard",
  true
);
