// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Switch } from "../components/wireframe/ui/switch.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSwitch = /* @__PURE__ */ wrapWireframe(
  "Switch",
  Switch,
  "switch"
);
