// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  TooltipProvider,
  TooltipWireframeExample,
} from "../components/wireframe/ui/tooltip.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeTooltip = /* @__PURE__ */ wrapWireframe(
  "Tooltip",
  Tooltip,
  "tooltip"
);
export const WireframeTooltipTrigger = /* @__PURE__ */ wrapWireframe(
  "TooltipTrigger",
  TooltipTrigger,
  "tooltip"
);
export const WireframeTooltipContent = /* @__PURE__ */ wrapWireframe(
  "TooltipContent",
  TooltipContent,
  "tooltip"
);
export const WireframeTooltipProvider = /* @__PURE__ */ wrapWireframe(
  "TooltipProvider",
  TooltipProvider,
  "tooltip"
);
export const WireframeTooltipWireframeExample = /* @__PURE__ */ wrapWireframe(
  "TooltipWireframeExample",
  TooltipWireframeExample,
  "tooltip"
);
