// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  CollapsibleWireframeExample,
} from "../components/wireframe/ui/collapsible.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeCollapsible = /* @__PURE__ */ wrapWireframe(
  "Collapsible",
  Collapsible,
  "collapsible"
);
export const WireframeCollapsibleTrigger = /* @__PURE__ */ wrapWireframe(
  "CollapsibleTrigger",
  CollapsibleTrigger,
  "collapsible"
);
export const WireframeCollapsibleContent = /* @__PURE__ */ wrapWireframe(
  "CollapsibleContent",
  CollapsibleContent,
  "collapsible"
);
export const WireframeCollapsibleWireframeExample =
  /* @__PURE__ */ wrapWireframe(
    "CollapsibleWireframeExample",
    CollapsibleWireframeExample,
    "collapsible"
  );
