// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Menubar,
  MenubarPortal,
  MenubarMenu,
  MenubarTrigger,
  MenubarContent,
  MenubarGroup,
  MenubarSeparator,
  MenubarLabel,
  MenubarItem,
  MenubarShortcut,
  MenubarCheckboxItem,
  MenubarRadioGroup,
  MenubarRadioItem,
  MenubarSub,
  MenubarSubTrigger,
  MenubarSubContent,
  MenubarWireframeExample,
} from "../components/wireframe/ui/menubar.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeMenubar = /* @__PURE__ */ wrapWireframe(
  "Menubar",
  Menubar,
  "menubar"
);
export const WireframeMenubarPortal = /* @__PURE__ */ wrapWireframe(
  "MenubarPortal",
  MenubarPortal,
  "menubar"
);
export const WireframeMenubarMenu = /* @__PURE__ */ wrapWireframe(
  "MenubarMenu",
  MenubarMenu,
  "menubar"
);
export const WireframeMenubarTrigger = /* @__PURE__ */ wrapWireframe(
  "MenubarTrigger",
  MenubarTrigger,
  "menubar"
);
export const WireframeMenubarContent = /* @__PURE__ */ wrapWireframe(
  "MenubarContent",
  MenubarContent,
  "menubar"
);
export const WireframeMenubarGroup = /* @__PURE__ */ wrapWireframe(
  "MenubarGroup",
  MenubarGroup,
  "menubar"
);
export const WireframeMenubarSeparator = /* @__PURE__ */ wrapWireframe(
  "MenubarSeparator",
  MenubarSeparator,
  "menubar"
);
export const WireframeMenubarLabel = /* @__PURE__ */ wrapWireframe(
  "MenubarLabel",
  MenubarLabel,
  "menubar"
);
export const WireframeMenubarItem = /* @__PURE__ */ wrapWireframe(
  "MenubarItem",
  MenubarItem,
  "menubar"
);
export const WireframeMenubarShortcut = /* @__PURE__ */ wrapWireframe(
  "MenubarShortcut",
  MenubarShortcut,
  "menubar"
);
export const WireframeMenubarCheckboxItem = /* @__PURE__ */ wrapWireframe(
  "MenubarCheckboxItem",
  MenubarCheckboxItem,
  "menubar"
);
export const WireframeMenubarRadioGroup = /* @__PURE__ */ wrapWireframe(
  "MenubarRadioGroup",
  MenubarRadioGroup,
  "menubar"
);
export const WireframeMenubarRadioItem = /* @__PURE__ */ wrapWireframe(
  "MenubarRadioItem",
  MenubarRadioItem,
  "menubar"
);
export const WireframeMenubarSub = /* @__PURE__ */ wrapWireframe(
  "MenubarSub",
  MenubarSub,
  "menubar"
);
export const WireframeMenubarSubTrigger = /* @__PURE__ */ wrapWireframe(
  "MenubarSubTrigger",
  MenubarSubTrigger,
  "menubar"
);
export const WireframeMenubarSubContent = /* @__PURE__ */ wrapWireframe(
  "MenubarSubContent",
  MenubarSubContent,
  "menubar"
);
export const WireframeMenubarWireframeExample = /* @__PURE__ */ wrapWireframe(
  "MenubarWireframeExample",
  MenubarWireframeExample,
  "menubar"
);
