// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  ButtonGroup,
  ButtonGroupSeparator,
  ButtonGroupText,
  ButtonGroupTextWireframe,
} from "../components/wireframe/ui/button-group.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeButtonGroup = /* @__PURE__ */ wrapWireframe(
  "ButtonGroup",
  ButtonGroup,
  "button-group"
);
export const WireframeButtonGroupSeparator = /* @__PURE__ */ wrapWireframe(
  "ButtonGroupSeparator",
  ButtonGroupSeparator,
  "button-group"
);
export const WireframeButtonGroupText = /* @__PURE__ */ wrapWireframe(
  "ButtonGroupText",
  ButtonGroupText,
  "button-group"
);
export const WireframeButtonGroupTextWireframe = /* @__PURE__ */ wrapWireframe(
  "ButtonGroupTextWireframe",
  ButtonGroupTextWireframe,
  "button-group"
);
