// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Form,
  FormItem,
  FormLabel,
  FormControl,
  FormDescription,
  FormMessage,
  FormField,
} from "../components/wireframe/ui/form.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeForm = /* @__PURE__ */ wrapWireframe(
  "Form",
  Form,
  "form"
);
export const WireframeFormItem = /* @__PURE__ */ wrapWireframe(
  "FormItem",
  FormItem,
  "form"
);
export const WireframeFormLabel = /* @__PURE__ */ wrapWireframe(
  "FormLabel",
  FormLabel,
  "form"
);
export const WireframeFormControl = /* @__PURE__ */ wrapWireframe(
  "FormControl",
  FormControl,
  "form"
);
export const WireframeFormDescription = /* @__PURE__ */ wrapWireframe(
  "FormDescription",
  FormDescription,
  "form"
);
export const WireframeFormMessage = /* @__PURE__ */ wrapWireframe(
  "FormMessage",
  FormMessage,
  "form"
);
export const WireframeFormField = /* @__PURE__ */ wrapWireframe(
  "FormField",
  FormField,
  "form"
);
