// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Empty,
  EmptyHeader,
  EmptyTitle,
  EmptyDescription,
  EmptyContent,
  EmptyMedia,
  EmptyTitleWireframe,
  EmptyDescriptionWireframe,
  EmptyMediaWireframe,
} from "../components/wireframe/ui/empty.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeEmpty = /* @__PURE__ */ wrapWireframe(
  "Empty",
  Empty,
  "empty"
);
export const WireframeEmptyHeader = /* @__PURE__ */ wrapWireframe(
  "EmptyHeader",
  EmptyHeader,
  "empty"
);
export const WireframeEmptyTitle = /* @__PURE__ */ wrapWireframe(
  "EmptyTitle",
  EmptyTitle,
  "empty"
);
export const WireframeEmptyDescription = /* @__PURE__ */ wrapWireframe(
  "EmptyDescription",
  EmptyDescription,
  "empty"
);
export const WireframeEmptyContent = /* @__PURE__ */ wrapWireframe(
  "EmptyContent",
  EmptyContent,
  "empty"
);
export const WireframeEmptyMedia = /* @__PURE__ */ wrapWireframe(
  "EmptyMedia",
  EmptyMedia,
  "empty"
);
export const WireframeEmptyTitleWireframe = /* @__PURE__ */ wrapWireframe(
  "EmptyTitleWireframe",
  EmptyTitleWireframe,
  "empty"
);
export const WireframeEmptyDescriptionWireframe = /* @__PURE__ */ wrapWireframe(
  "EmptyDescriptionWireframe",
  EmptyDescriptionWireframe,
  "empty"
);
export const WireframeEmptyMediaWireframe = /* @__PURE__ */ wrapWireframe(
  "EmptyMediaWireframe",
  EmptyMediaWireframe,
  "empty"
);
