// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { ContactForm } from "../components/wireframe/blocks/contact-form.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeContactForm = /* @__PURE__ */ wrapWireframe(
  "ContactForm",
  ContactForm,
  "contact-form",
  true
);
