// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Field,
  FieldLabel,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldContent,
  FieldTitle,
  FieldLabelWireframe,
  FieldDescriptionWireframe,
} from "../components/wireframe/ui/file.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeField = /* @__PURE__ */ wrapWireframe(
  "Field",
  Field,
  "file"
);
export const WireframeFieldLabel = /* @__PURE__ */ wrapWireframe(
  "FieldLabel",
  FieldLabel,
  "file"
);
export const WireframeFieldDescription = /* @__PURE__ */ wrapWireframe(
  "FieldDescription",
  FieldDescription,
  "file"
);
export const WireframeFieldError = /* @__PURE__ */ wrapWireframe(
  "FieldError",
  FieldError,
  "file"
);
export const WireframeFieldGroup = /* @__PURE__ */ wrapWireframe(
  "FieldGroup",
  FieldGroup,
  "file"
);
export const WireframeFieldLegend = /* @__PURE__ */ wrapWireframe(
  "FieldLegend",
  FieldLegend,
  "file"
);
export const WireframeFieldSeparator = /* @__PURE__ */ wrapWireframe(
  "FieldSeparator",
  FieldSeparator,
  "file"
);
export const WireframeFieldSet = /* @__PURE__ */ wrapWireframe(
  "FieldSet",
  FieldSet,
  "file"
);
export const WireframeFieldContent = /* @__PURE__ */ wrapWireframe(
  "FieldContent",
  FieldContent,
  "file"
);
export const WireframeFieldTitle = /* @__PURE__ */ wrapWireframe(
  "FieldTitle",
  FieldTitle,
  "file"
);
export const WireframeFieldLabelWireframe = /* @__PURE__ */ wrapWireframe(
  "FieldLabelWireframe",
  FieldLabelWireframe,
  "file"
);
export const WireframeFieldDescriptionWireframe = /* @__PURE__ */ wrapWireframe(
  "FieldDescriptionWireframe",
  FieldDescriptionWireframe,
  "file"
);
