// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Alert,
  AlertTitle,
  AlertDescription,
  AlertWireframe,
} from "../components/wireframe/ui/alert.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeAlert = /* @__PURE__ */ wrapWireframe(
  "Alert",
  Alert,
  "alert"
);
export const WireframeAlertTitle = /* @__PURE__ */ wrapWireframe(
  "AlertTitle",
  AlertTitle,
  "alert"
);
export const WireframeAlertDescription = /* @__PURE__ */ wrapWireframe(
  "AlertDescription",
  AlertDescription,
  "alert"
);
export const WireframeAlertWireframe = /* @__PURE__ */ wrapWireframe(
  "AlertWireframe",
  AlertWireframe,
  "alert"
);
