// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
} from "../components/wireframe/ui/select.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSelect = /* @__PURE__ */ wrapWireframe(
  "Select",
  Select,
  "select"
);
export const WireframeSelectContent = /* @__PURE__ */ wrapWireframe(
  "SelectContent",
  SelectContent,
  "select"
);
export const WireframeSelectGroup = /* @__PURE__ */ wrapWireframe(
  "SelectGroup",
  SelectGroup,
  "select"
);
export const WireframeSelectItem = /* @__PURE__ */ wrapWireframe(
  "SelectItem",
  SelectItem,
  "select"
);
export const WireframeSelectLabel = /* @__PURE__ */ wrapWireframe(
  "SelectLabel",
  SelectLabel,
  "select"
);
export const WireframeSelectScrollDownButton = /* @__PURE__ */ wrapWireframe(
  "SelectScrollDownButton",
  SelectScrollDownButton,
  "select"
);
export const WireframeSelectScrollUpButton = /* @__PURE__ */ wrapWireframe(
  "SelectScrollUpButton",
  SelectScrollUpButton,
  "select"
);
export const WireframeSelectSeparator = /* @__PURE__ */ wrapWireframe(
  "SelectSeparator",
  SelectSeparator,
  "select"
);
export const WireframeSelectTrigger = /* @__PURE__ */ wrapWireframe(
  "SelectTrigger",
  SelectTrigger,
  "select"
);
export const WireframeSelectValue = /* @__PURE__ */ wrapWireframe(
  "SelectValue",
  SelectValue,
  "select"
);
