// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { RegisterForm } from "../components/wireframe/blocks/register-form.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeRegisterForm = /* @__PURE__ */ wrapWireframe(
  "RegisterForm",
  RegisterForm,
  "register-form",
  true
);
