// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Item,
  ItemMedia,
  ItemContent,
  ItemActions,
  ItemGroup,
  ItemSeparator,
  ItemTitle,
  ItemDescription,
  ItemHeader,
  ItemFooter,
  ItemTitleWireframe,
  ItemDescriptionWireframe,
  ItemMediaWireframe,
} from "../components/wireframe/ui/item.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeItem = /* @__PURE__ */ wrapWireframe(
  "Item",
  Item,
  "item"
);
export const WireframeItemMedia = /* @__PURE__ */ wrapWireframe(
  "ItemMedia",
  ItemMedia,
  "item"
);
export const WireframeItemContent = /* @__PURE__ */ wrapWireframe(
  "ItemContent",
  ItemContent,
  "item"
);
export const WireframeItemActions = /* @__PURE__ */ wrapWireframe(
  "ItemActions",
  ItemActions,
  "item"
);
export const WireframeItemGroup = /* @__PURE__ */ wrapWireframe(
  "ItemGroup",
  ItemGroup,
  "item"
);
export const WireframeItemSeparator = /* @__PURE__ */ wrapWireframe(
  "ItemSeparator",
  ItemSeparator,
  "item"
);
export const WireframeItemTitle = /* @__PURE__ */ wrapWireframe(
  "ItemTitle",
  ItemTitle,
  "item"
);
export const WireframeItemDescription = /* @__PURE__ */ wrapWireframe(
  "ItemDescription",
  ItemDescription,
  "item"
);
export const WireframeItemHeader = /* @__PURE__ */ wrapWireframe(
  "ItemHeader",
  ItemHeader,
  "item"
);
export const WireframeItemFooter = /* @__PURE__ */ wrapWireframe(
  "ItemFooter",
  ItemFooter,
  "item"
);
export const WireframeItemTitleWireframe = /* @__PURE__ */ wrapWireframe(
  "ItemTitleWireframe",
  ItemTitleWireframe,
  "item"
);
export const WireframeItemDescriptionWireframe = /* @__PURE__ */ wrapWireframe(
  "ItemDescriptionWireframe",
  ItemDescriptionWireframe,
  "item"
);
export const WireframeItemMediaWireframe = /* @__PURE__ */ wrapWireframe(
  "ItemMediaWireframe",
  ItemMediaWireframe,
  "item"
);
