// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { SettingsPage } from "../components/wireframe/blocks/settings-page.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSettingsPage = /* @__PURE__ */ wrapWireframe(
  "SettingsPage",
  SettingsPage,
  "settings-page",
  true
);
