// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Textarea } from "../components/wireframe/ui/textarea.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeTextarea = /* @__PURE__ */ wrapWireframe(
  "Textarea",
  Textarea,
  "textarea"
);
