// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { ProfilePage } from "../components/wireframe/blocks/profile-page.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeProfilePage = /* @__PURE__ */ wrapWireframe(
  "ProfilePage",
  ProfilePage,
  "profile-page",
  true
);
