// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselPrevious,
  CarouselNext,
  CarouselItemWireframe,
} from "../components/wireframe/ui/carousel.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeCarousel = /* @__PURE__ */ wrapWireframe(
  "Carousel",
  Carousel,
  "carousel"
);
export const WireframeCarouselContent = /* @__PURE__ */ wrapWireframe(
  "CarouselContent",
  CarouselContent,
  "carousel"
);
export const WireframeCarouselItem = /* @__PURE__ */ wrapWireframe(
  "CarouselItem",
  CarouselItem,
  "carousel"
);
export const WireframeCarouselPrevious = /* @__PURE__ */ wrapWireframe(
  "CarouselPrevious",
  CarouselPrevious,
  "carousel"
);
export const WireframeCarouselNext = /* @__PURE__ */ wrapWireframe(
  "CarouselNext",
  CarouselNext,
  "carousel"
);
export const WireframeCarouselItemWireframe = /* @__PURE__ */ wrapWireframe(
  "CarouselItemWireframe",
  CarouselItemWireframe,
  "carousel"
);
