// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
  SheetTitleWireframe,
  SheetDescriptionWireframe,
} from "../components/wireframe/ui/sheet.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSheet = /* @__PURE__ */ wrapWireframe(
  "Sheet",
  Sheet,
  "sheet"
);
export const WireframeSheetTrigger = /* @__PURE__ */ wrapWireframe(
  "SheetTrigger",
  SheetTrigger,
  "sheet"
);
export const WireframeSheetClose = /* @__PURE__ */ wrapWireframe(
  "SheetClose",
  SheetClose,
  "sheet"
);
export const WireframeSheetContent = /* @__PURE__ */ wrapWireframe(
  "SheetContent",
  SheetContent,
  "sheet"
);
export const WireframeSheetHeader = /* @__PURE__ */ wrapWireframe(
  "SheetHeader",
  SheetHeader,
  "sheet"
);
export const WireframeSheetFooter = /* @__PURE__ */ wrapWireframe(
  "SheetFooter",
  SheetFooter,
  "sheet"
);
export const WireframeSheetTitle = /* @__PURE__ */ wrapWireframe(
  "SheetTitle",
  SheetTitle,
  "sheet"
);
export const WireframeSheetDescription = /* @__PURE__ */ wrapWireframe(
  "SheetDescription",
  SheetDescription,
  "sheet"
);
export const WireframeSheetTitleWireframe = /* @__PURE__ */ wrapWireframe(
  "SheetTitleWireframe",
  SheetTitleWireframe,
  "sheet"
);
export const WireframeSheetDescriptionWireframe = /* @__PURE__ */ wrapWireframe(
  "SheetDescriptionWireframe",
  SheetDescriptionWireframe,
  "sheet"
);
