// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  HoverCard,
  HoverCardTrigger,
  HoverCardContent,
  HoverCardWireframeExample,
} from "../components/wireframe/ui/hover-card.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeHoverCard = /* @__PURE__ */ wrapWireframe(
  "HoverCard",
  HoverCard,
  "hover-card"
);
export const WireframeHoverCardTrigger = /* @__PURE__ */ wrapWireframe(
  "HoverCardTrigger",
  HoverCardTrigger,
  "hover-card"
);
export const WireframeHoverCardContent = /* @__PURE__ */ wrapWireframe(
  "HoverCardContent",
  HoverCardContent,
  "hover-card"
);
export const WireframeHoverCardWireframeExample = /* @__PURE__ */ wrapWireframe(
  "HoverCardWireframeExample",
  HoverCardWireframeExample,
  "hover-card"
);
