// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import { Slider } from "../components/wireframe/ui/slider.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeSlider = /* @__PURE__ */ wrapWireframe(
  "Slider",
  Slider,
  "slider"
);
