// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Text,
  TextHeading,
  TextParagraph,
  TextCaption,
  TextLabel,
} from "../components/wireframe/ui/text.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeText = /* @__PURE__ */ wrapWireframe(
  "Text",
  Text,
  "text"
);
export const WireframeTextHeading = /* @__PURE__ */ wrapWireframe(
  "TextHeading",
  TextHeading,
  "text"
);
export const WireframeTextParagraph = /* @__PURE__ */ wrapWireframe(
  "TextParagraph",
  TextParagraph,
  "text"
);
export const WireframeTextCaption = /* @__PURE__ */ wrapWireframe(
  "TextCaption",
  TextCaption,
  "text"
);
export const WireframeTextLabel = /* @__PURE__ */ wrapWireframe(
  "TextLabel",
  TextLabel,
  "text"
);
