// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  Avatar,
  AvatarImage,
  AvatarFallback,
} from "../components/wireframe/ui/avatar.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeAvatar = /* @__PURE__ */ wrapWireframe(
  "Avatar",
  Avatar,
  "avatar"
);
export const WireframeAvatarImage = /* @__PURE__ */ wrapWireframe(
  "AvatarImage",
  AvatarImage,
  "avatar"
);
export const WireframeAvatarFallback = /* @__PURE__ */ wrapWireframe(
  "AvatarFallback",
  AvatarFallback,
  "avatar"
);
