// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.
/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */
import {
  ContextMenu,
  ContextMenuTrigger,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuCheckboxItem,
  ContextMenuRadioItem,
  ContextMenuLabel,
  ContextMenuSeparator,
  ContextMenuShortcut,
  ContextMenuGroup,
  ContextMenuPortal,
  ContextMenuSub,
  ContextMenuSubContent,
  ContextMenuSubTrigger,
  ContextMenuRadioGroup,
  ContextMenuItemWireframe,
  ContextMenuLabelWireframe,
} from "../components/wireframe/ui/context-menu.js";
import { wrapWireframe } from "../wireframe/component.js";

export const WireframeContextMenu = /* @__PURE__ */ wrapWireframe(
  "ContextMenu",
  ContextMenu,
  "context-menu"
);
export const WireframeContextMenuTrigger = /* @__PURE__ */ wrapWireframe(
  "ContextMenuTrigger",
  ContextMenuTrigger,
  "context-menu"
);
export const WireframeContextMenuContent = /* @__PURE__ */ wrapWireframe(
  "ContextMenuContent",
  ContextMenuContent,
  "context-menu"
);
export const WireframeContextMenuItem = /* @__PURE__ */ wrapWireframe(
  "ContextMenuItem",
  ContextMenuItem,
  "context-menu"
);
export const WireframeContextMenuCheckboxItem = /* @__PURE__ */ wrapWireframe(
  "ContextMenuCheckboxItem",
  ContextMenuCheckboxItem,
  "context-menu"
);
export const WireframeContextMenuRadioItem = /* @__PURE__ */ wrapWireframe(
  "ContextMenuRadioItem",
  ContextMenuRadioItem,
  "context-menu"
);
export const WireframeContextMenuLabel = /* @__PURE__ */ wrapWireframe(
  "ContextMenuLabel",
  ContextMenuLabel,
  "context-menu"
);
export const WireframeContextMenuSeparator = /* @__PURE__ */ wrapWireframe(
  "ContextMenuSeparator",
  ContextMenuSeparator,
  "context-menu"
);
export const WireframeContextMenuShortcut = /* @__PURE__ */ wrapWireframe(
  "ContextMenuShortcut",
  ContextMenuShortcut,
  "context-menu"
);
export const WireframeContextMenuGroup = /* @__PURE__ */ wrapWireframe(
  "ContextMenuGroup",
  ContextMenuGroup,
  "context-menu"
);
export const WireframeContextMenuPortal = /* @__PURE__ */ wrapWireframe(
  "ContextMenuPortal",
  ContextMenuPortal,
  "context-menu"
);
export const WireframeContextMenuSub = /* @__PURE__ */ wrapWireframe(
  "ContextMenuSub",
  ContextMenuSub,
  "context-menu"
);
export const WireframeContextMenuSubContent = /* @__PURE__ */ wrapWireframe(
  "ContextMenuSubContent",
  ContextMenuSubContent,
  "context-menu"
);
export const WireframeContextMenuSubTrigger = /* @__PURE__ */ wrapWireframe(
  "ContextMenuSubTrigger",
  ContextMenuSubTrigger,
  "context-menu"
);
export const WireframeContextMenuRadioGroup = /* @__PURE__ */ wrapWireframe(
  "ContextMenuRadioGroup",
  ContextMenuRadioGroup,
  "context-menu"
);
export const WireframeContextMenuItemWireframe = /* @__PURE__ */ wrapWireframe(
  "ContextMenuItemWireframe",
  ContextMenuItemWireframe,
  "context-menu"
);
export const WireframeContextMenuLabelWireframe = /* @__PURE__ */ wrapWireframe(
  "ContextMenuLabelWireframe",
  ContextMenuLabelWireframe,
  "context-menu"
);
