#!/usr/bin/env node
// Sync docs demo pages with the per-section fragments produced by
// `pnpm docs:demos` (render-examples.ts --split).
//
//   * docs/docs/extended/<family>.mdx (+ ja/): drops the page-top
//     Preview/Code Tabs that showed the whole family document, and points
//     each `## N. Component` section's Preview iframe at that component's
//     own fragment (extended-<family>--<slug>.html).
//   * docs/docs/components.mdx (+ ja/): replaces each family's single
//     Preview/Code Tabs with per-section `###` subsections whose iframes
//     target <base>--<slug>.html and whose Code tab inlines the section's
//     own mdx source. Generated regions are wrapped in `{/* demo:<base> */}`
//     markers so reruns regenerate them in place.
//
// Reads docs/public/components/sections.json — run `pnpm docs:demos` first.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import * as v from "valibot";

const root = path.resolve(import.meta.dirname, "..");
const manifestPath = path.join(root, "docs/public/components/sections.json");
if (!existsSync(manifestPath)) {
  console.error("mdxr: sections.json missing — run `pnpm docs:demos` first");
  process.exit(1);
}
const manifestSchema = v.record(
  v.string(),
  v.object({
    sections: v.array(
      v.object({ slug: v.string(), source: v.string(), title: v.string() })
    ),
    title: v.string(),
  })
);
type Manifest = v.InferOutput<typeof manifestSchema>;
type SectionInfo = Manifest[string]["sections"][number];
const manifest = v.parse(
  manifestSchema,
  JSON.parse(readFileSync(manifestPath, "utf-8"))
);

const slugify = (title: string): string =>
  title
    .toLowerCase()
    .replaceAll(/[^\p{L}\p{N}]+/gu, "-")
    .replaceAll(/^-+|-+$/gu, "");

const IFRAME_STYLE =
  "width:100%;height:480px;border:1px solid #d4d4d8;border-radius:8px;background:#fff";

/** Fence long enough that backtick runs inside `source` can't close it. */
const codeFence = (source: string): string => {
  let longest = 0;
  for (const run of source.matchAll(/`+/gu)) {
    longest = Math.max(longest, run[0].length);
  }
  return "`".repeat(Math.max(4, longest + 1));
};

const tabsLabels = (ja: boolean): { code: string; preview: string } =>
  ja
    ? { code: "コード", preview: "プレビュー" }
    : { code: "Code", preview: "Preview" };

/** The generated `###` subsections for one catalog document. */
const demoBlock = (
  base: string,
  sections: SectionInfo[],
  ja: boolean
): string => {
  const { preview, code } = tabsLabels(ja);
  const parts = sections.map((section) => {
    const fence = codeFence(section.source);
    return `### ${section.title}

<Tabs syncKey="components-${base}-${section.slug}">
  <Tab title="${preview}">

<iframe src={\`\${import.meta.env.BASE_URL}/components/${base}--${section.slug}.html\`} title="${section.title}" loading="lazy" style="${IFRAME_STYLE}" />

  </Tab>
  <Tab title="${code}">

${fence}mdx
${section.source}
${fence}

  </Tab>
</Tabs>
`;
  });
  return `{/* demo:${base} — regenerated by scripts/sync-demo-pages.ts */}\n\n${parts.join("\n\n")}\n{/* /demo:${base} */}`;
};

/** Escape a `regex.source` fragment — catalog doc names are `[a-z-]+`. */
const transformComponentsPage = (page: string, ja: boolean): string => {
  let out = page;
  for (const [base, entry] of Object.entries(manifest)) {
    if (entry.sections.length === 0) {
      continue;
    }
    const marker = new RegExp(
      `\\{/\\* demo:${base}[^}]*\\*/\\}[\\s\\S]*?\\{/\\* /demo:${base} \\*/\\}`,
      "u"
    );
    if (marker.test(out)) {
      out = out.replace(marker, () => demoBlock(base, entry.sections, ja));
      continue;
    }
    const tabs = new RegExp(
      `<Tabs syncKey="components-${base}">\\n[\\s\\S]*?</Tabs>\\n`,
      "u"
    );
    if (tabs.test(out)) {
      out = out.replace(tabs, () => `${demoBlock(base, entry.sections, ja)}\n`);
    }
  }
  return out;
};

/**
 * Extended page: remove the family-wide top Tabs and retarget each
 * `## N. Component` section's Preview iframe to its fragment.
 */
const transformExtendedPage = (page: string, fam: string): string => {
  const entry = manifest[`extended-${fam}`];
  if (entry === undefined) {
    return page;
  }
  // The first Tabs block is the family-wide one — drop it plus a trailing
  // blank line so the page flows straight into the component sections.
  let out = page.replace(
    new RegExp(
      `<Tabs syncKey="components-extended-${fam}">\\n[\\s\\S]*?</Tabs>\\n\\n?`,
      "u"
    ),
    ""
  );
  const base = `extended-${fam}`;
  // Collect each `## N. Title` section's fragment slug in document order so
  // the matching `.html#anchor` URL below can be rewritten by position.
  const slugs: string[] = [];
  let index = 0;
  out = out.replaceAll(
    /^## \d+\. (?<title>.+)$/gmu,
    (heading: string, title: string) => {
      const section = entry.sections[index];
      index += 1;
      if (section === undefined) {
        console.warn(`mdxr: ${base}: no manifest section for "${title}"`);
        return heading;
      }
      if (slugify(title) !== section.slug) {
        console.warn(
          `mdxr: ${base}: manifest section ${index} is "${section.title}" but page says "${title}" — check ordering`
        );
      }
      slugs.push(section.slug);
      return heading;
    }
  );
  let i = 0;
  return out.replaceAll(
    new RegExp(`/components/${base}\\.html#[a-z0-9-]+`, "gu"),
    () => {
      const slug = slugs[i] ?? "section";
      i += 1;
      return `/components/${base}--${slug}.html`;
    }
  );
};

let changed = 0;
const writeIfChanged = (file: string, content: string): void => {
  if (readFileSync(file, "utf-8") !== content) {
    writeFileSync(file, content);
    changed += 1;
    console.log(`mdxr: synced ${path.relative(root, file)}`);
  }
};

for (const locale of ["", "ja/"]) {
  const ja = locale === "ja/";
  const componentsPage = path.join(root, "docs/docs", locale, "components.mdx");
  writeIfChanged(
    componentsPage,
    transformComponentsPage(readFileSync(componentsPage, "utf-8"), ja)
  );
  const extendedDir = path.join(root, "docs/docs", locale, "extended");
  for (const file of readdirSync(extendedDir)) {
    if (!file.endsWith(".mdx")) {
      continue;
    }
    const fam = file.replace(/\.mdx$/u, "");
    const page = path.join(extendedDir, file);
    writeIfChanged(
      page,
      transformExtendedPage(readFileSync(page, "utf-8"), fam)
    );
  }
}
console.log(`mdxr: ${changed} docs page(s) synced`);
