// Regenerate the mdxr leaf adapters after updating the pinned upstream manifest.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import * as v from "valibot";

const root = path.resolve(import.meta.dirname, "..");
const { families } = v.parse(
  v.object({
    families: v.array(
      v.object({
        components: v.array(v.string()),
        kind: v.picklist(["ui", "block"]),
        name: v.string(),
      })
    ),
  }),
  JSON.parse(
    await readFile(path.join(root, "src/wireframe/registry.json"), "utf-8")
  )
);

const aliases: Record<string, Record<string, string>> = {
  chart: { WireframeChart: "WireframeChartWireframe" },
  "list-group": { WireframeList: "WireframeListGroup" },
};
const imports: string[] = [];
const maps: string[] = [];
const publicExports: string[] = [];

await Promise.all(
  families.map(async ({ components, kind, name }) => {
    const alias = aliases[name] ?? {};
    const names = components.map((component) => `Wireframe${component}`);
    const lines = [
      "// Generated by scripts/sync-wireframe-catalog.ts from the pinned upstream registry.",
      "/* oxlint-disable no-inline-comments -- @__PURE__ tells bundlers to omit unused component adapters; this annotation must directly precede the call. */",
      `import { ${components.join(", ")} } from "../components/wireframe/${kind === "ui" ? "ui" : "blocks"}/${name}.js";`,
      'import { wrapWireframe } from "../wireframe/component.js";',
      "",
      ...components.map(
        (component) =>
          `export const Wireframe${component} = /* @__PURE__ */ wrapWireframe("${component}", ${component}, "${name}"${kind === "block" ? ", true" : ""});`
      ),
      ...Object.entries(alias).map(
        ([key, value]) => `export const ${key} = ${value};`
      ),
      "",
    ];
    await writeFile(
      path.join(root, `src/ui/wireframe-library-${name}.tsx`),
      lines.join("\n")
    );
    return names;
  })
);

for (const { components, name } of families) {
  const variable = name.replaceAll(
    /(?:^|-)(?<letter>[a-z])/gu,
    (_, letter: string) => letter.toUpperCase()
  );
  imports.push(
    `import * as ${variable} from "./wireframe-library-${name}.js";`
  );
  maps.push(`  ...${variable},`);
  const names = [
    ...components.map((component) => `Wireframe${component}`),
    ...Object.keys(aliases[name] ?? {}),
  ];
  publicExports.push(
    `export { ${names.join(", ")} } from "./wireframe-library-${name}.js";`
  );
}
await writeFile(
  path.join(root, "src/ui/wireframe-library-catalog.ts"),
  [
    'import type { ComponentMap } from "../define.js";',
    ...imports,
    "",
    "export const wireframeComponents: ComponentMap = {",
    ...maps,
    "};",
    "",
  ].join("\n")
);
const entryPath = path.join(root, "src/ui/index.ts");
const previousEntry = await readFile(entryPath, "utf-8");
const entry = previousEntry
  .replaceAll(
    /export \{[^{}]*\} from "\.\/wireframe-library-[a-z-]+\.js";\n/gu,
    ""
  )
  .trimEnd();
await writeFile(entryPath, `${entry}\n\n${publicExports.join("\n")}\n`);
