/** The 120 proposed feature families; child components share their parent entry. */
export const EXTENDED_FEATURES = [
  {
    category: "evidence",
    components: ["Sources", "Source", "Cite"],
    name: "Sources",
    number: 1,
  },
  {
    category: "evidence",
    components: ["CrossRef"],
    name: "CrossRef",
    number: 2,
  },
  {
    category: "evidence",
    components: ["Evidence"],
    name: "Evidence",
    number: 3,
  },
  {
    category: "evidence",
    components: ["Provenance"],
    name: "Provenance",
    number: 4,
  },
  {
    category: "evidence",
    components: ["Assumptions"],
    name: "Assumptions",
    number: 5,
  },
  {
    category: "evidence",
    components: ["Limitations"],
    name: "Limitations",
    number: 6,
  },
  {
    category: "evidence",
    components: ["Sidenote"],
    name: "Sidenote",
    number: 7,
  },
  {
    category: "evidence",
    components: ["TermRef"],
    name: "TermRef",
    number: 8,
  },
  {
    category: "evidence",
    components: ["Include"],
    name: "Include",
    number: 9,
  },
  {
    category: "evidence",
    components: ["DocumentHistory"],
    name: "DocumentHistory",
    number: 10,
  },
  {
    category: "planning",
    components: ["Traceability"],
    name: "Traceability",
    number: 11,
  },
  {
    category: "planning",
    components: ["DecisionMatrix"],
    name: "DecisionMatrix",
    number: 12,
  },
  {
    category: "planning",
    components: ["RiskRegister"],
    name: "RiskRegister",
    number: 13,
  },
  {
    category: "planning",
    components: ["Scope"],
    name: "Scope",
    number: 14,
  },
  {
    category: "planning",
    components: ["ActionItems"],
    name: "ActionItems",
    number: 15,
  },
  {
    category: "planning",
    components: ["Estimate"],
    name: "Estimate",
    number: 16,
  },
  {
    category: "planning",
    components: ["DependencyPlan"],
    name: "DependencyPlan",
    number: 17,
  },
  {
    category: "planning",
    components: ["RACI"],
    name: "RACI",
    number: 18,
  },
  {
    category: "planning",
    components: ["Objectives", "KeyResults"],
    name: "Objectives",
    number: 19,
  },
  {
    category: "planning",
    components: ["CapacityPlan"],
    name: "CapacityPlan",
    number: 20,
  },
  {
    category: "investigation",
    components: ["Reproduction"],
    name: "Reproduction",
    number: 21,
  },
  {
    category: "investigation",
    components: ["Logs"],
    name: "Logs",
    number: 22,
  },
  {
    category: "investigation",
    components: ["JsonDiff"],
    name: "JsonDiff",
    number: 23,
  },
  {
    category: "investigation",
    components: ["ConfigDiff"],
    name: "ConfigDiff",
    number: 24,
  },
  {
    category: "investigation",
    components: ["ApiDiff"],
    name: "ApiDiff",
    number: 25,
  },
  {
    category: "investigation",
    components: ["SchemaDiff"],
    name: "SchemaDiff",
    number: 26,
  },
  {
    category: "investigation",
    components: ["ImpactMap"],
    name: "ImpactMap",
    number: 27,
  },
  {
    category: "investigation",
    components: ["DataLineage"],
    name: "DataLineage",
    number: 28,
  },
  {
    category: "investigation",
    components: ["SymbolOutline"],
    name: "SymbolOutline",
    number: 29,
  },
  {
    category: "investigation",
    components: ["CodeWalkthrough"],
    name: "CodeWalkthrough",
    number: 30,
  },
  {
    category: "reference",
    components: ["CodeGroup"],
    name: "CodeGroup",
    number: 31,
  },
  {
    category: "reference",
    components: ["PackageInstall"],
    name: "PackageInstall",
    number: 32,
  },
  {
    category: "reference",
    components: ["ApiExample", "Request", "Response"],
    name: "ApiExample",
    number: 33,
  },
  {
    category: "reference",
    components: ["ApiParams"],
    name: "ApiParams",
    number: 34,
  },
  {
    category: "reference",
    components: ["ObjectSchema"],
    name: "ObjectSchema",
    number: 35,
  },
  {
    category: "reference",
    components: ["CliReference"],
    name: "CliReference",
    number: 36,
  },
  {
    category: "reference",
    components: ["ConfigReference"],
    name: "ConfigReference",
    number: 37,
  },
  {
    category: "reference",
    components: ["ErrorCatalog"],
    name: "ErrorCatalog",
    number: 38,
  },
  {
    category: "reference",
    components: ["CompatibilityMatrix"],
    name: "CompatibilityMatrix",
    number: 39,
  },
  {
    category: "reference",
    components: ["DeprecationTimeline"],
    name: "DeprecationTimeline",
    number: 40,
  },
  {
    category: "quality",
    components: ["TestMatrix"],
    name: "TestMatrix",
    number: 41,
  },
  {
    category: "quality",
    components: ["Coverage"],
    name: "Coverage",
    number: 42,
  },
  {
    category: "quality",
    components: ["BenchmarkSuite"],
    name: "BenchmarkSuite",
    number: 43,
  },
  {
    category: "quality",
    components: ["TestHistory"],
    name: "TestHistory",
    number: 44,
  },
  {
    category: "quality",
    components: ["VisualDiff"],
    name: "VisualDiff",
    number: 45,
  },
  {
    category: "quality",
    components: ["AccessibilityReport"],
    name: "AccessibilityReport",
    number: 46,
  },
  {
    category: "quality",
    components: ["BundleReport"],
    name: "BundleReport",
    number: 47,
  },
  {
    category: "quality",
    components: ["Flamegraph"],
    name: "Flamegraph",
    number: 48,
  },
  {
    category: "quality",
    components: ["QueryPlan"],
    name: "QueryPlan",
    number: 49,
  },
  {
    category: "quality",
    components: ["ContractResults"],
    name: "ContractResults",
    number: 50,
  },
  {
    category: "operations",
    components: ["Runbook"],
    name: "Runbook",
    number: 51,
  },
  {
    category: "operations",
    components: ["Rollout"],
    name: "Rollout",
    number: 52,
  },
  {
    category: "operations",
    components: ["SLO", "ErrorBudget"],
    name: "SLO",
    number: 53,
  },
  {
    category: "operations",
    components: ["AlertRules"],
    name: "AlertRules",
    number: 54,
  },
  {
    category: "operations",
    components: ["FeatureFlags"],
    name: "FeatureFlags",
    number: 55,
  },
  {
    category: "operations",
    components: ["RecoveryPlan"],
    name: "RecoveryPlan",
    number: 56,
  },
  {
    category: "operations",
    components: ["PermissionMatrix"],
    name: "PermissionMatrix",
    number: 57,
  },
  {
    category: "operations",
    components: ["ThreatModel"],
    name: "ThreatModel",
    number: 58,
  },
  {
    category: "operations",
    components: ["Remediation"],
    name: "Remediation",
    number: 59,
  },
  {
    category: "operations",
    components: ["MaintenanceWindow"],
    name: "MaintenanceWindow",
    number: 60,
  },
  {
    category: "statistics",
    components: ["Heatmap"],
    name: "Heatmap",
    number: 61,
  },
  {
    category: "statistics",
    components: ["Histogram"],
    name: "Histogram",
    number: 62,
  },
  {
    category: "statistics",
    components: ["BoxPlot"],
    name: "BoxPlot",
    number: 63,
  },
  {
    category: "statistics",
    components: ["ECDF"],
    name: "ECDF",
    number: 64,
  },
  {
    category: "statistics",
    components: ["IntervalPlot"],
    name: "IntervalPlot",
    number: 65,
  },
  {
    category: "statistics",
    components: ["BulletChart"],
    name: "BulletChart",
    number: 66,
  },
  {
    category: "statistics",
    components: ["CalendarHeatmap"],
    name: "CalendarHeatmap",
    number: 67,
  },
  {
    category: "statistics",
    components: ["ParetoChart"],
    name: "ParetoChart",
    number: 68,
  },
  {
    category: "statistics",
    components: ["CohortTable"],
    name: "CohortTable",
    number: 69,
  },
  {
    category: "statistics",
    components: ["ConfusionMatrix"],
    name: "ConfusionMatrix",
    number: 70,
  },
  {
    category: "charts",
    components: ["ViolinPlot"],
    name: "ViolinPlot",
    number: 71,
  },
  {
    category: "charts",
    components: ["RidgelinePlot"],
    name: "RidgelinePlot",
    number: 72,
  },
  {
    category: "charts",
    components: ["DotPlot"],
    name: "DotPlot",
    number: 73,
  },
  {
    category: "charts",
    components: ["SlopeChart"],
    name: "SlopeChart",
    number: 74,
  },
  {
    category: "charts",
    components: ["BumpChart"],
    name: "BumpChart",
    number: 75,
  },
  {
    category: "charts",
    components: ["DumbbellChart"],
    name: "DumbbellChart",
    number: 76,
  },
  {
    category: "charts",
    components: ["Sunburst"],
    name: "Sunburst",
    number: 77,
  },
  {
    category: "charts",
    components: ["ChordDiagram"],
    name: "ChordDiagram",
    number: 78,
  },
  {
    category: "charts",
    components: ["UpSetPlot"],
    name: "UpSetPlot",
    number: 79,
  },
  {
    category: "charts",
    components: ["SmallMultiples"],
    name: "SmallMultiples",
    number: 80,
  },
  {
    category: "diagrams",
    components: ["SequenceDiagram"],
    name: "SequenceDiagram",
    number: 81,
  },
  {
    category: "diagrams",
    components: ["StateDiagram"],
    name: "StateDiagram",
    number: 82,
  },
  {
    category: "diagrams",
    components: ["EntityRelations"],
    name: "EntityRelations",
    number: 83,
  },
  {
    category: "diagrams",
    components: ["Swimlane"],
    name: "Swimlane",
    number: 84,
  },
  {
    category: "diagrams",
    components: ["Architecture"],
    name: "Architecture",
    number: 85,
  },
  {
    category: "diagrams",
    components: ["DecisionTree"],
    name: "DecisionTree",
    number: 86,
  },
  {
    category: "diagrams",
    components: ["MindMap"],
    name: "MindMap",
    number: 87,
  },
  {
    category: "diagrams",
    components: ["JourneyMap"],
    name: "JourneyMap",
    number: 88,
  },
  {
    category: "diagrams",
    components: ["ServiceTopology"],
    name: "ServiceTopology",
    number: 89,
  },
  {
    category: "diagrams",
    components: ["DependencyMatrix"],
    name: "DependencyMatrix",
    number: 90,
  },
  {
    category: "interactive",
    components: ["DataTable"],
    name: "DataTable",
    number: 91,
  },
  {
    category: "interactive",
    components: ["FilterPanel"],
    name: "FilterPanel",
    number: 92,
  },
  {
    category: "interactive",
    components: ["Checklist"],
    name: "Checklist",
    number: 93,
  },
  {
    category: "interactive",
    components: ["Ranking"],
    name: "Ranking",
    number: 94,
  },
  {
    category: "interactive",
    components: ["Calculator"],
    name: "Calculator",
    number: 95,
  },
  {
    category: "interactive",
    components: ["Wizard"],
    name: "Wizard",
    number: 96,
  },
  {
    category: "interactive",
    components: ["SyncedTabs", "TabItem"],
    name: "SyncedTabs",
    number: 97,
  },
  {
    category: "interactive",
    components: ["DocumentSearch"],
    name: "DocumentSearch",
    number: 98,
  },
  {
    category: "interactive",
    components: ["AnswerSheet"],
    name: "AnswerSheet",
    number: 99,
  },
  {
    category: "interactive",
    components: ["DownloadData"],
    name: "DownloadData",
    number: 100,
  },
  {
    category: "media",
    components: ["ImageGallery"],
    name: "ImageGallery",
    number: 101,
  },
  {
    category: "media",
    components: ["AnnotatedImage"],
    name: "AnnotatedImage",
    number: 102,
  },
  {
    category: "media",
    components: ["ImageCompare"],
    name: "ImageCompare",
    number: 103,
  },
  {
    category: "media",
    components: ["Video"],
    name: "Video",
    number: 104,
  },
  {
    category: "media",
    components: ["AudioTranscript"],
    name: "AudioTranscript",
    number: 105,
  },
  {
    category: "media",
    components: ["PdfPreview"],
    name: "PdfPreview",
    number: 106,
  },
  {
    category: "media",
    components: ["PrintLayout", "PageBreak"],
    name: "PrintLayout",
    number: 107,
  },
  {
    category: "media",
    components: ["TableOfFigures"],
    name: "TableOfFigures",
    number: 108,
  },
  {
    category: "media",
    components: ["NumberedEquation"],
    name: "NumberedEquation",
    number: 109,
  },
  {
    category: "media",
    components: ["Theorem", "Proof"],
    name: "Theorem",
    number: 110,
  },
  {
    category: "evaluation",
    components: ["EvalReport", "EvalCase"],
    name: "EvalReport",
    number: 111,
  },
  {
    category: "evaluation",
    components: ["ModelComparison"],
    name: "ModelComparison",
    number: 112,
  },
  {
    category: "evaluation",
    components: ["Conversation"],
    name: "Conversation",
    number: 113,
  },
  {
    category: "evaluation",
    components: ["ToolCall"],
    name: "ToolCall",
    number: 114,
  },
  {
    category: "evaluation",
    components: ["TokenUsage"],
    name: "TokenUsage",
    number: 115,
  },
  {
    category: "evaluation",
    components: ["PromptTemplate"],
    name: "PromptTemplate",
    number: 116,
  },
  {
    category: "evaluation",
    components: ["DatasetProfile"],
    name: "DatasetProfile",
    number: 117,
  },
  {
    category: "evaluation",
    components: ["DataValidation"],
    name: "DataValidation",
    number: 118,
  },
  {
    category: "evaluation",
    components: ["Experiment"],
    name: "Experiment",
    number: 119,
  },
  {
    category: "evaluation",
    components: ["DatasetDiff"],
    name: "DatasetDiff",
    number: 120,
  },
] as const;
